version: "3"

services:
  database:
    container_name: sql-database
    build: ./database/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root-psw
    restart: always
    tty: true

  app:
    container_name: app
    build: ./app/
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    command: npm run dev
    depends_on:
      - database
    tty: true
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 3001:80
    environment:
      PMA_HOST: database
    depends_on:
      - database
